# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* account_yodlee
# 
# Translators:
# Martin Trigaux, 2019
# Rick Hunter <rick.hunter.ec@gmail.com>, 2019
# Jon Perez <jop@odoo.com>, 2019
# Victoria Quesada <victoria.quesada@nybblegroup.com>, 2020
# 
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~12.5+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-26 08:04+0000\n"
"PO-Revision-Date: 2019-08-26 09:34+0000\n"
"Last-Translator: Victoria Quesada <victoria.quesada@nybblegroup.com>, 2020\n"
"Language-Team: Spanish (https://www.transifex.com/odoo/teams/41243/es/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: es\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "(Diagnostic: %r for URL %s)"
msgstr "(Diagnóstico: %r para URL %s)"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Account"
msgstr "Cuenta"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Already Registered (436):Your Auto-Registration could not be "
"completed because the site reports that your account is already registered."
"  Please log in to the site to confirm and then complete the site addition "
"process with the correct login information."
msgstr ""
"Cuenta ya registrada (436): No se puede completar su registro automático "
"debido a que el sitio informa que su cuenta ya se encuentra registrada. "
"Inicie sesión en el sitio para confirmar  y luego completar el proceso de "
"adición al portal con la información de inicio de sesión correcta."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Locked (407): We could not update your account because it appears "
"your account has been locked. This usually results from too many "
"unsuccessful login attempts in a short period of time. Please visit the site"
" or contact its customer support to resolve this issue.  Once done, please "
"update your account credentials in case they are changed."
msgstr ""
"Cuenta bloqueada (407): No pudimos actualizar su cuenta porque parece que su"
" cuenta ha sido bloqueada. Esto generalmente es resultado de demasiados "
"intentos fallidos de inicio de sesión en un corto período de tiempo. Visite "
"el sitio o póngase en contacto con su departamento de atención al cliente "
"para resolver este problema. Una vez hecho esto, actualice las credenciales "
"de su cuenta en caso de que hayan cambiado."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Not Found(408): We're sorry, we couldn't find any accounts for you "
"at the site. Please log in at the site and confirm that your account is set "
"up, then try again."
msgstr ""
"Cuenta no encontrada (408): Lo sentimos, no pudimos encontrar cuenta alguna "
"a su nombre en el sitio. Inicie sesión en el sitio y confirme que su cuenta "
"esté configurada, luego de ello intente de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Reported Closed (422): We were unable to update your account "
"information because it appears one or more of your related accounts have "
"been closed.  Please deactivate or delete the relevant account and try "
"again."
msgstr ""
"Cuenta reportada como cerrada (422): No pudimos actualizar la información de"
" su cuenta, puesto que al parecer una o mas de sus cuentas relacionadas se "
"han cerrado. Desactive o elimine la cuenta respectiva e intente de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Type Not Supported(417):The type of account we found is not "
"currently supported.  Please remove this site and add as a  manual account."
msgstr ""
"Tipo de cuenta no admitido(417): El tipo de cuenta que encontramos no se "
"admite actualmente. Retire este sitio y agréguelo como una cuenta manual."

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Active/Inactive on Yodlee system"
msgstr "Activo/Inactivo en el sistema Yodlee"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "An Error has occurred (code %s)"
msgstr "Se ha producido un error (code %s)"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_res_company
msgid "Companies"
msgstr "Compañías"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Could not make sense of parameters: %s"
msgstr "No se comprenden los parametros"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (402): We could not update your account "
"because your username and/or password were reported to be incorrect.  Please"
" re-verify your username and password."
msgstr ""
"Se requiere volver a verificar la credencial (402): No pudimos actualizar su"
" cuenta debido a que su nombre de usuario o contraseña se reportaron como "
"incorrectos. Verifique de nuevo su nombre de usuario y contraseña."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (420):The site has merged with another. "
"Please re-verify your credentials at the site and update the same."
msgstr ""
"Se require verificar de nuevo la credencial (420): El sitio se ha fusionado "
"con otro. Vuelva a verificar sus credenciales y actualícelas."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s"
msgstr "%sMensaje%s de error:"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s, reference code: %s"
msgstr "Error: %s, mensaje: %s, código de referencia: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Home Value Not Found (511): The site is unable to provide home value for "
"your property. We suggest you to delete this site."
msgstr ""
"No se encontró el valor de la vivienda (511): El sitio no ha podido "
"suministrar un valor de vivienda para su propiedad. Le sugerimos que elimine"
" este sitio."

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_journal
msgid "Interface for Online Account Journal"
msgstr "Interfaz para el diario de cuenta en línea"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Invalid Language Setting (421): The language setting for your site account "
"is not English. Please visit the site and change the language setting to "
"English."
msgstr ""
"Ajuste inválido de idioma (421): El ajuste de idioma para su cuenta de sitio"
" no está en inglés. Visite el sitio y cambie el ajuste de idioma a inglés."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Additional Authentication Enrollment Required (521) : Please "
"enroll in the new security authentication system, <Account Name> has "
"introduced. Ensure your account settings in <Cobrand> are updated with this "
"information."
msgstr ""
"Error MFA: Se requiere de inscripción de autenticación adicional ( 521): "
"Inscríbase en el nuevo sistema de autenticación de seguridad, se ha "
"introducido <Account Name>. Asegúrese de que sus ajustes de cuenta en "
"<Conrand> estén actualizados con esta información."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Expired (524):We're sorry, the "
"authentication information you provided has expired. Please try again."
msgstr ""
"Error MFA: Ha vencido la información de autenticación (524): Lo sentimos, la"
" información de autenticación que suministró ha vencido. Inténtelo de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (520):We're sorry, the site "
"indicates that the additional authentication information you provided is "
"incorrect. Please try updating your account again."
msgstr ""
"Error MFA: Información de autenticación incorrecta (520): Lo sentimos, el "
"sitio indica que la información adicional de autenticación que usted "
"suministró es incorrecta. Intente actualizar su cuenta de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (523):We're sorry, the "
"authentication information you  provided is incorrect. Please try again."
msgstr ""
"Error MFA: Información de autenticación incorrecta (523): Lo sentimos, la "
"información de autenticación que suministró es incorrecta. Intente de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Required (519): Your account was not "
"updated as your authentication information like security question and answer"
" was unavailable or incomplete. Please update your account settings."
msgstr ""
"Error MFA: Se requiere de información de autenticación (519): Su cuenta no "
"se actualizó puesto que su información de autenticación como la pregunta de "
"seguridad y su respuesta no estaban disponibles o estaban incompletas. "
"Actualice los ajustes de su cuenta."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Unavailable (518):Your account was not"
" updated as the required additional authentication information was "
"unavailable. Please try now."
msgstr ""
"Error MFA: Información de autenticación no disponible (518): No se actualizó"
" su cuenta, puesto que la información adicional de autenticación requerida "
"no estaba disponible. Intente de nuevo ahora."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Credential Re-Verification Required (526): We could not update "
"your account because your username/password or additional security "
"credentials are incorrect. Please try again."
msgstr ""
"Error MFA: Se requiere verificar de nuevo la credencial (526): No pudimos "
"actualizar si cuenta, debido a que su nombre de usuario, contraseña o las "
"credenciales adicionales de seguridad son incorrectas. Intente de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Problem Updating Account (525): We could not update your account "
"for technical reasons. This type of error is usually resolved in a few days."
" We apologize for the inconvenience. Please try again later."
msgstr ""
"Error MFA: Problema al actualizar al cuenta (525): No pudimos actualizar su "
"cuenta debido a razones técnica. Este tipo de error se resuelve usualmente "
"en pocos días. Nos disculpamos por el inconveniente. Intente de nuevo más "
"tarde."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Request Timed Out (522) :Your request has timed out as the "
"required security information was unavailable or was not provided within the"
" expected time. Please try again."
msgstr ""
"Error MFA: Se agotó el tiempo de su solicitud ( 522): Se ha agotado el "
"tiempo para su solicitud, debido a que la información de seguridad no estaba"
" disponible o no se suministró dentro del tiempo esperado. Intente de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Site Device Information Expired(509): We're sorry, we can't "
"update your account because your token is no longer valid at the site. "
"Please update your information and try again, or contact customer support."
msgstr ""
"Error MFA: Se venció la información del dispositivo del sitio (509): Lo "
"sentimos, no podemos actualizar su cuenta, puesto que su palabra de acceso "
"(token) ya no es válida para este sitio. Actualice su información e intente "
"de nuevo, o póngase en contacto con atención al cliente."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Multiple User Logins(416): We attempted to update your account, but another "
"session was already established at the same time.  If you are currently "
"logged on to this account directly, please log off and try after some time"
msgstr ""
"Múltiples inicios de sesión de usuario (416): Intentamos actualizar su "
"cuenta, pero ya se había establecido otra sesión al mismo tiempo. Si tiene "
"una sesión iniciada directamente en esta cuenta en este momento, cierre la "
"sesión e intente de nuevo más tarde."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"New Login Information Required(506):We're sorry, to log in to this site, you"
" need to provide additional information. Please update your account and try "
"again."
msgstr ""
"Se requiere de nueva información de inicio de sesión (506): Lo sentimos, "
"para iniciar sesión en este sitio, es necesario suministrar información "
"adicional. Actualice su cuenta en inténtelo de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Account Found (423): We were unable to detect an account. Please verify "
"that you account information is available at this time and If the problem "
"persists, please contact customer support at online@odoo.com for further "
"assistance."
msgstr ""
"No se encontró una cuenta (423): No pudimos detectar una cuenta. Verifique "
"que la información de su cuenta esté disponible en este momento y si el "
"problema persiste, póngase en contacto con servicio al cliente al correo "
"online@odoo.com para mayor asistencia."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Payees Found(512):Your request cannot be completed as no payees were "
"found in your account."
msgstr ""
"No se encontraron beneficiarios (512): No se puede completar la solicitud "
"porque no se encontraron beneficiarios en su cuenta."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Online institution"
msgstr "Institución virtual"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Please configure an email in the company settings."
msgstr ""
"Configure una dirección de correo electrónico en los ajustes de empresa."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (406): We could not update your account because the"
" site requires you to perform some additional action. Please visit the site "
"or contact its customer support to resolve this issue. Once done, please "
"update your account credentials in case they are changed else try again."
msgstr ""
"Problema al actualizar la cuenta (406): No pudimos actualizar su cuenta "
"debido a que el sitio requiere que usted realice alguna acción adicional. "
"Visite el sitio o póngase en contacto con su servicio al cliente para "
"resolver este problema. Una vez  hecho esto, actualice las credenciales de "
"su cuenta en caso de que hayan cambiado, de lo contrario intente de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (517): We are sorry, there was a technical problem "
"updating your account. Please try again."
msgstr ""
"Problema de actualización de cuenta (517): Lo sentimos pero hubo un problema"
" técnico al actualizar su cuenta. Por favor inténtelo nuevamente. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(401):We're sorry, your request timed out. Please "
"try again."
msgstr ""
"Problema al actualizar la cuenta (401): Lo sentimos, se agotó el tiempo para"
" su solicitud. Intente de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(403):We're sorry, there was a technical problem "
"updating your account. This kind of error is usually resolved in a few days."
" Please try again later."
msgstr ""
"Problema al actualizar la cuenta (403): Lo sentimos, ocurrió un problema "
"técnico al actualizar su cuenta. Este tipo de error usualmente se resuelve "
"en pocos días. Intente de nuevo más tarde."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(404):We're sorry, there was a technical problem "
"updating your account. Please try again later."
msgstr ""
"Problema al actualizar la cuenta (404): Lo sentimos, ocurrió in problema "
"técnico al actualizar su cuenta. Intente de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(409): We could not update your account because the "
"end site is experiencing technical difficulties."
msgstr ""
"Problema al actualizar la cuenta (409): No pudimos actualizar su cuenta "
"debido a que el sitio final está experimentando dificultades técnicas."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(412): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Problema al actualizar la cuenta (412): No pudimos actualizar su cuenta "
"debido a que el sitio está experimentando dificultades técnicas."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(413):We're sorry, we couldn't update your account "
"at the site because of a technical issue. This type of problem is usually "
"resolved in a few days. Please try again later."
msgstr ""
"Problema al actualizar la cuenta (413): Lo sentimos, no pudimos actualizar "
"su cuenta en el sitio debido a un problema técnico. Este tipo de error "
"usualmente se resuelve en pocos días. Intente de nuevo más tarde."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(415): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Problema al actualizar la cuenta (415): No pudimos actualizar su cuenta "
"debido a que el sitio está experimentando dificultades técnicas."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(418): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Problema al actualizar la cuenta (418): No pudimos actualizar su cuenta "
"debido a que el sitio está experimentando dificultades técnicas. Inténtelo "
"más tarde."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(419):We're sorry, we couldn't update your account "
"because of unexpected variations at the site. This kind of problem is "
"usually resolved in a few days. Please try again later."
msgstr ""
"Problema al actualizar la cuenta (413): Lo sentimos, no pudimos actualizar "
"su cuenta debido a variaciones inesperadas en el sitio. Este tipo de "
"problema usualmente se resuelve en pocos días. Intente de nuevo más tarde."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(425): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Problema al actualizar la cuenta (425): No pudimos actualizar su cuenta "
"debido a que el sitio está experimentando dificultades técnicas. Inténtelo "
"más tarde."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(426): We could not update your account for "
"technical reasons. This type of error is usually resolved in a few days. We "
"apologize for the inconvenience."
msgstr ""
"Problema al actualizar al cuenta (426): No pudimos actualizar su cuenta "
"debido a razones técnica. Este tipo de error se resuelve usualmente en pocos"
" días. Nos disculpamos por el inconveniente."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(507):We're sorry, Yodlee has just started providing"
" data updates for this site, and it may take a few days to be successful as "
"we get started. Please try again later."
msgstr ""
"Problema al actualizar la cuenta (507): Lo sentimos, Yodlee acaba de "
"comenzar a suministrar actualizaciones de datos para este sitio, y tomará "
"pocos minutos para generar resultados a medida que iniciamos. Intente de "
"nuevo más tarde."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Property Record Not Found (510): The site is unable to find any property "
"information for your address. Please verify if the property address you have"
" provided is correct."
msgstr ""
"No se encontró el registro de propiedad (501): Este sitio no pudo encontrar "
"cualquier información de propiedad para su dirección. Verifique si la "
"dirección de propiedad que suministró es correcta."

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider__provider_type
msgid "Provider Type"
msgstr "Tipo de Proveedor"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr "Proveedor de sincronización de cuenta en línea"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-Verification Required (429): We could not update your account due to the "
"site requiring you to verify your personal information. Please log in to the"
" site and update the fields required."
msgstr ""
"Se requiere volver a verificar (429): No pudimos actualizar su cuenta debido"
" a que el sitio requiere que usted verifique su información personal. Inicie"
" sesión en el sitio y actualice los campos requeridos."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (427): We could not update your account due to the "
"site requiring you to view a new promotion. Please log in to the site and "
"click through to your account overview page to update the account.  We "
"apologize for the inconvenience."
msgstr ""
"Se requiere volver a verificar (427): No pudimos actualizar su cuenta debido"
" a que el sitio requiere que usted vea una promoción nueva. Inicie sesión en"
" el sitio y haga clic a lo largo de su página de resumen de cuenta para "
"actualizar la cuenta. Nos disculpamos por el inconveniente."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (428): We could not update your account due to the "
"site requiring you to accept a new Terms & Conditions. Please log in to the "
"site and read and accept the T&C."
msgstr ""
"Se requiere volver a verificar (429): No pudimos actualizar su cuenta debido"
" a que el sitio requiere que usted acepte los nuevos Términos y Condiciones."
" Inicie sesión en el sitio y acepte los Términos y Condiciones."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (433): Auto registration is not complete. "
"Please complete your registration at the end site. Once completed, please "
"complete adding this account."
msgstr ""
"El registro requiere de atención (433): No se completó el registro "
"automático. Complete su registro en el sitio final. Una vez lo haya "
"completado, complete la adición de esta cuenta."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (434): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"Inscripción Requiere Atención (434): Su Auto-Inscripción podría no ser "
"completada y requiere entradas posteriores. Por favor verifique una vez más "
"su información de inscripción para completar el proceso."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (435): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"Inscripción Requiere Atención (435): Su Auto-Inscripción podría no ser "
"completada y requiere entradas posteriores. Por favor verifique una vez más "
"su información de inscripción para completar el proceso."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Request Timed Out (508): We are sorry, your request timed out due to "
"technical reasons. Please try again."
msgstr ""
"Solicitud Fuera de Tiempo (508): Lo sentimos, su solicitud esta fuera de "
"tiempo debido a razones técnicas. Por favor intente de nuevo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Requested Account Type Not Found (414): We could not find your requested "
"account. You may have selected a similar site under a different category by "
"accident in which case you should select the correct site."
msgstr ""
"Tipo de Cuenta Solicitada No Encontrada (414): No pudimos encontrar su "
"cuenta solicitada. Pudo haber seleccionado, por accidente, un sitio similar "
"bajo una categoría diferente, en cual caso debe seleccionar el sitio "
"correcto."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Server not reachable, please try again later"
msgstr ""
"No se puede acceder al servidor, por favor intente otra vez más tarde. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Down for Maintenance(424):We were unable to update your account as the "
"site is temporarily down for maintenance. We apologize for the "
"inconvenience.  This problem is typically resolved in a few hours. Please "
"try later."
msgstr ""
"Sitio Dado de Baja por Mantenimiento (424): Fuimos inhabilitados para "
"actualizar su cuenta ya que el sitio esta temporalmente dado de baja por "
"mantenimiento. Nos disculpamos por el inconveniente. Este problema esta "
"resuelto normalmente dentro de algunas horas. Por favor intente más tarde."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Available (411):The site no longer provides online services "
"to its customers.  Please delete this account."
msgstr ""
"Sitio Ya No Disponible (411): El sitio ya no provee servicios en línea a sus"
" clientes. Por favor elimine esta cuenta."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Supported (430):This site is no longer supported for data "
"updates. Please deactivate or delete your account. We apologize for the "
"inconvenience."
msgstr ""
"Sitio Ya No Soportado (430). Este sitio ya no es soportado para "
"actualizaciones de datos. Por favor desactive o elimine su cuenta. Nos "
"disculpamos por el inconveniente. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Not Supported (505): We currently does not support the security system "
"used by this site. We apologize for any inconvenience. Check back "
"periodically if this situation has changed."
msgstr ""
"Sitio No Soportado (505): Actualmente no soportamos el sistema de seguridad "
"usado por este sitio. Nos disculpamos por cualquier inconveniente. Revise "
"periódicamente si esta situación ha cambiado."

#. module: account_yodlee
#: model:ir.actions.client,name:account_yodlee.yodlee_widget
msgid "Synchronization process completed"
msgstr "Proceso de sincronización completo"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Timeout: the server did not reply within 30s"
msgstr "Tiempo de espera agotado: el servidor no ha respondido en 30s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Update Request Canceled(405):Your account was not updated because you "
"canceled the request."
msgstr ""
"Solicitud de Actualización Cancelada (405): Su cuenta no fue actualizada "
"porque canceló la solicitud."

#. module: account_yodlee
#: model:ir.model.fields.selection,name:account_yodlee.selection__account_online_provider__provider_type__yodlee
msgid "Yodlee"
msgstr "Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Yodlee Account Status"
msgstr "Estado de la cuenta Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_status_code
msgid "Yodlee Status Code"
msgstr "Código del estado de Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_access_token
msgid "Yodlee access token"
msgstr "Palabra de acceso de Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_login
msgid "Yodlee login"
msgstr "Usuario de Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_password
msgid "Yodlee password"
msgstr "Contraseña de Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_access_token
msgid "access_token"
msgstr "access_token"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "message: %s"
msgstr "mensaje: %s"
