# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* account_yodlee
# 
# Translators:
# Francesco Garganese <francesco.garganese@aeromnia.aero>, 2019
# Martin Trigaux, 2019
# Giovanni Perteghella <giovanni@perteghella.org>, 2019
# Paolo Valier, 2019
# Léonie Bouchat <lbo@odoo.com>, 2019
# Sergio Zanchetta <primes2h@gmail.com>, 2020
# 
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~12.5+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-26 08:04+0000\n"
"PO-Revision-Date: 2019-08-26 09:34+0000\n"
"Last-Translator: Sergio Zanchetta <primes2h@gmail.com>, 2020\n"
"Language-Team: Italian (https://www.transifex.com/odoo/teams/41243/it/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: it\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "(Diagnostic: %r for URL %s)"
msgstr "(Diagnostica: %r per URL %s)"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Account"
msgstr "Conto"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Already Registered (436):Your Auto-Registration could not be "
"completed because the site reports that your account is already registered."
"  Please log in to the site to confirm and then complete the site addition "
"process with the correct login information."
msgstr ""
"Account già registrato (436): Non è stato possibile completare la "
"registrazione automatica perché il tuo account è gia registrato su questo "
"sito. Connettiti sul sito per confermare e completare il processo di "
"aggiunta del sito con le informazioni di accesso corrette. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Locked (407): We could not update your account because it appears "
"your account has been locked. This usually results from too many "
"unsuccessful login attempts in a short period of time. Please visit the site"
" or contact its customer support to resolve this issue.  Once done, please "
"update your account credentials in case they are changed."
msgstr ""
"Account bloccato (407): Non abbiamo potuto aggiornare il tuo account perché "
"sembra che sia stato bloccato. Questo è solitamente il risultato di troppi "
"tentativi di connessioni fallite in un breve periodo di tempo. Per risolvere"
" questo problema, visita il sito o contatta il servizio clienti. Una volta "
"risolto il problema, aggiorna le credenziali di accesso nel caso in cui sono"
" state modificate."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Not Found(408): We're sorry, we couldn't find any accounts for you "
"at the site. Please log in at the site and confirm that your account is set "
"up, then try again."
msgstr ""
"Account non trovato (408): Siamo spiacenti, non abbiamo trovato alcun "
"account per te sul sito. Accedi al sito e conferma che il tuo account è "
"stato configurato, poi riprova. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Reported Closed (422): We were unable to update your account "
"information because it appears one or more of your related accounts have "
"been closed.  Please deactivate or delete the relevant account and try "
"again."
msgstr ""
"Account chiuso (422): Non abbiamo potuto aggiornare i dati del tuo account "
"perché sembra che uno o più dei tuoi account siano stati chiusi. Disattiva o"
" elimina gli account corrispondenti e riprova."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Type Not Supported(417):The type of account we found is not "
"currently supported.  Please remove this site and add as a  manual account."
msgstr ""
"Tipo di account non supportato (417): Il tipo di account trovato non è "
"attualmente supportato. Rimuovi questo sito e aggiungilo come account "
"manuale.  "

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Active/Inactive on Yodlee system"
msgstr "Attivo/Inattivo sul sistema Yodlee"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "An Error has occurred (code %s)"
msgstr "Si è verificato un problema (codice %s)"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_res_company
msgid "Companies"
msgstr "Aziende"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Could not make sense of parameters: %s"
msgstr ""

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (402): We could not update your account "
"because your username and/or password were reported to be incorrect.  Please"
" re-verify your username and password."
msgstr ""
"Nuova verifica delle credenziali richiesta (402): Non abbiamo potuto "
"aggiornare il tuo account perché il tuo nome utente e/o la tua password sono"
" stati segnalati come non corretti. Verifica di nuovo il tuo nome utente e "
"la tua password. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (420):The site has merged with another. "
"Please re-verify your credentials at the site and update the same."
msgstr ""
"Nuova verifica delle credenziali richiesta (420): Il sito si è fuso con un "
"altro. Controlla di nuovo le credenziali sul sito e aggiornale. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s"
msgstr "Errore %s, messaggio: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s, reference code: %s"
msgstr "Errore %s, messaggio: %s, codice riferimento: %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Home Value Not Found (511): The site is unable to provide home value for "
"your property. We suggest you to delete this site."
msgstr ""
"Valore delle casa non trovato (511): Il sito non può fornire un valore per "
"la tua proprietà. Ti consigliamo di cancellare questo sito. "

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_journal
msgid "Interface for Online Account Journal"
msgstr "Interfaccia per il registro contabile online"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Invalid Language Setting (421): The language setting for your site account "
"is not English. Please visit the site and change the language setting to "
"English."
msgstr ""
"Impostazione di lingua non valida (421): Il tuo account di sito non è "
"impostato in inglese. Visita il sito e cambia l'impostazione di lingua in "
"inglese. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Additional Authentication Enrollment Required (521) : Please "
"enroll in the new security authentication system, <Account Name> has "
"introduced. Ensure your account settings in <Cobrand> are updated with this "
"information."
msgstr ""
"Errore di autenticazione multifattoriale: Registrazione ad una "
"autenticazione aggiuntiva richiesta (521): Registrati al nuovo sistema di "
"autenticazione di sicurezza che <Account Name> ha implementato. Assicurati "
"che le impostazioni del tuo account in <Cobrand> siano aggiornate con queste"
" informazioni. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Expired (524):We're sorry, the "
"authentication information you provided has expired. Please try again."
msgstr ""
"Errore di autenticazione multifattoriale: Informazioni di autenticazione "
"scadute (524): Siamo spiacenti, le informazioni di autenticazione fornite "
"sono scadute. Prova di nuovo. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (520):We're sorry, the site "
"indicates that the additional authentication information you provided is "
"incorrect. Please try updating your account again."
msgstr ""
"Errore di autenticazione multifattoriale: Informazioni di autenticazione non"
" corrette (520): Siamo spiacenti, il sito indica che le informazioni di "
"autenticazione aggiuntive fornite non sono corrette. Prova di nuovo e "
"aggiorna il tuo account. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (523):We're sorry, the "
"authentication information you  provided is incorrect. Please try again."
msgstr ""
"Errore di autenticazione multifattoriale (523): Siamo spiacenti, le "
"informazioni di autenticazione fornite non sono corrette. Prova di nuovo. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Required (519): Your account was not "
"updated as your authentication information like security question and answer"
" was unavailable or incomplete. Please update your account settings."
msgstr ""
"Errore di autenticazione multifattoriale: Informazioni di autenticazione "
"richieste (519): l'account non è stato aggiornato perché le informazioni di "
"autenticazione, come la domanda e la risposta di sicurezza, non erano "
"disponibili o erano incomplete. Aggiorna le impostazioni del tuo account. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Unavailable (518):Your account was not"
" updated as the required additional authentication information was "
"unavailable. Please try now."
msgstr ""
"Errore di autenticazione multifattoriale: Informazioni di autenticazione non"
" disponibili (518): Il tuo account non è stato aggiornato perché le "
"informazioni di autenticazione aggiuntive non erano disponibili. Prova di "
"nuovo adesso. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Credential Re-Verification Required (526): We could not update "
"your account because your username/password or additional security "
"credentials are incorrect. Please try again."
msgstr ""
"Errore di autenticazione multifattoriale: Nuova verifica dei credenziali "
"richiesta (526): Non abbiamo potuto aggiornare il tuo account perché il tuo "
"nome utente/ la tua password o le credenziali di sicurezza aggiuntive non "
"sono corrette. Prova di nuovo. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Problem Updating Account (525): We could not update your account "
"for technical reasons. This type of error is usually resolved in a few days."
" We apologize for the inconvenience. Please try again later."
msgstr ""
"Errore du autenticazione multifttoriale: Problema nell'aggiornamento "
"dell'account (525): Per motivi tecnici, non abbiamo potuto aggiornare i tuo "
"account. Questo tipo di errore viene solitamente risolto in alcuni giorni. "
"Ci scusiamo per il disagio. Riprova più tardi. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Request Timed Out (522) :Your request has timed out as the "
"required security information was unavailable or was not provided within the"
" expected time. Please try again."
msgstr ""
"Errore di autenticazione multifattoriale: Termine scaduto per la richiesta "
"(522): La tua richiesta è scaduta perché le informazioni di sicurezza "
"richieste non erano disponibili o non sono state fornite entro il termine "
"previsto. Prova di nuovo. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Site Device Information Expired(509): We're sorry, we can't "
"update your account because your token is no longer valid at the site. "
"Please update your information and try again, or contact customer support."
msgstr ""
"Errore di autenticazione multifattoriale: informazioni sul dispositivo del "
"sito scadute (509): Siamo spiacenti, non possiamo aggiornare il tuo account "
"perché il tuo token non è più valido sul sito. Aggiorna le tue informazioni "
"e riprova o contatta il servizio clienti."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Multiple User Logins(416): We attempted to update your account, but another "
"session was already established at the same time.  If you are currently "
"logged on to this account directly, please log off and try after some time"
msgstr ""
"Login di diversi utenti (416): Abbiamo cercato di aggiornare il tuo account,"
" ma un'altra sessione era aperta allo stesso momento. Se sei attualmente "
"loggato a questo account, esci e riprova dopo un po' di tempo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"New Login Information Required(506):We're sorry, to log in to this site, you"
" need to provide additional information. Please update your account and try "
"again."
msgstr ""
"Nuove informazioni di login richieste (506): Siamo spiacenti. Per fare il "
"login su questo sito, è necessario fornire ulteriori informazioni. Aggiorna "
"il tuo account e prova di nuovo."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Account Found (423): We were unable to detect an account. Please verify "
"that you account information is available at this time and If the problem "
"persists, please contact customer support at online@odoo.com for further "
"assistance."
msgstr ""
"Nessun account trovato (423): Non abbiamo trovato alcun account. Verifica "
"che le informazioni del tuo account siano attualmente disponibili e, se il "
"problema persiste, contatta il servizio clienti all'indirizzo "
"online@odoo.com. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Payees Found(512):Your request cannot be completed as no payees were "
"found in your account."
msgstr ""
"Beneficiari non trovati (512): Impossibile rispondere alla tua richiesta "
"perché non è stato trovato alcun beneficiario sul tuo conto. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Online institution"
msgstr "Istituzione online"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Please configure an email in the company settings."
msgstr "Configura una e-mail nelle configurazioni dell'azienda."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (406): We could not update your account because the"
" site requires you to perform some additional action. Please visit the site "
"or contact its customer support to resolve this issue. Once done, please "
"update your account credentials in case they are changed else try again."
msgstr ""
"Problema durante l'aggiornamento del tuo account (406): Non abbiamo potuto "
"aggiornare il tuo account perché il sito richiede un ulteriore intervento da"
" parte tua. Per risolvere questo problema, visita il sito o contatta il "
"servizio clienti. Una volta risolto il problema, aggiorna le credenziali del"
" tuo account se sono cambiate o riprova. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (517): We are sorry, there was a technical problem "
"updating your account. Please try again."
msgstr ""
"Problema durante l'aggiornamento dell'account (517): Siamo spiacenti. Si è "
"verificato un problema tecnico durante l'aggiornamento dell'account. Prova "
"di nuovo. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(401):We're sorry, your request timed out. Please "
"try again."
msgstr ""
"Problema durante l'aggiornamento dell'account (401): Siamo spiacenti, la tua"
" richiesta è scaduta. Prova di nuovo. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(403):We're sorry, there was a technical problem "
"updating your account. This kind of error is usually resolved in a few days."
" Please try again later."
msgstr ""
"Problema durante l'aggiornamento dell'account (403): Siamo spiacenti, si è "
"verificato un errore tecnico durante l'aggiornamento del tuo account. Questo"
" tipo di errore viene solitamente risolto in alcuni giorni. Prova di nuovo "
"più tardi. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(404):We're sorry, there was a technical problem "
"updating your account. Please try again later."
msgstr ""
"Problema durante l'aggiornamento del'account (404): Siamo spiacenti, si è "
"verificato un errore tecnico durante l'aggiornamento del tuo account. Prova "
"di nuovo più tardi. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(409): We could not update your account because the "
"end site is experiencing technical difficulties."
msgstr ""
"Problema durante l'aggiornamento dell'account (409): Non abbiamo potuto "
"aggiornare il tuo account, perché il sito finale sta attualmente incontrando"
" difficoltà tecniche. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(412): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Problema durante l'aggiornamento dell'account (412): Non abbiamo potuto "
"aggiornare il tuo account, perché il sito sta attualmente incontrando "
"difficoltà tecniche. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(413):We're sorry, we couldn't update your account "
"at the site because of a technical issue. This type of problem is usually "
"resolved in a few days. Please try again later."
msgstr ""
"Problema durante l'aggiornamento dell'account (413): Per motivi tecnici, non"
" abbiamo potuto aggiornare il tuo account. Questo tipo di problema viene "
"solitamente risolto in alcuni giorni. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(415): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr ""
"Problema durante l'aggiornamento dell'account (415): Non abbiamo potuto "
"aggiornare il tuo account, perché il sito sta attualmente incontrando "
"difficoltà tecniche. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(418): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Problema durante l'aggiornamento dell'account (418): Non abbiamo potuto "
"aggiornare il tuo account, perché il sito sta attualmente incontrando "
"difficoltà tecniche. Prova di nuovo più tardi. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(419):We're sorry, we couldn't update your account "
"because of unexpected variations at the site. This kind of problem is "
"usually resolved in a few days. Please try again later."
msgstr ""
"Problema durante l'aggiornamento dell'account (419): Siamo spiacenti, non "
"abbiamo potuto aggiornare il tuo account a causa di variazioni inaspettate "
"sul sito. Questo tipo di problema viene solitamente risolto in alcuni "
"giorni. Prova di nuovo più tardi. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(425): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr ""
"Problema durante l'aggiornamento dell'account (425): Non abbiamo potuto "
"aggiornare il tuo account perché il sito sta incontrando difficoltà "
"tecniche. Prova più tardi. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(426): We could not update your account for "
"technical reasons. This type of error is usually resolved in a few days. We "
"apologize for the inconvenience."
msgstr ""
"Problema nell'aggiornamento dell'account (426): Per motivi tecnici, non "
"abbiamo potuto aggiornare i tuo account. Questo tipo di errore viene "
"solitamente risolto in alcuni giorni. Ci scusiamo per il disagio. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(507):We're sorry, Yodlee has just started providing"
" data updates for this site, and it may take a few days to be successful as "
"we get started. Please try again later."
msgstr ""
"Problema durante l'aggiornamento dell'account (507): Siamo spiacenti, Yodlee"
" sta appena iniziando a fornire gli aggiornamenti dei dati per questo sito e"
" potrebbero essere necessari diversi giorni. Prova di nuovo più tardi. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Property Record Not Found (510): The site is unable to find any property "
"information for your address. Please verify if the property address you have"
" provided is correct."
msgstr ""
"Record della proprietà non trovato (510): Il sito non riesce a trovare alcun"
" informazione sulla proprietà del tuo indirizzo. Verifica l'esattezza "
"dell'indirizzo fornito per la proprietà. "

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider__provider_type
msgid "Provider Type"
msgstr "Tipo fornitore"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr "Fornitore per la sincronizzazione account online"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-Verification Required (429): We could not update your account due to the "
"site requiring you to verify your personal information. Please log in to the"
" site and update the fields required."
msgstr ""
"Nuova verifica richiesta (429): Non abbiamo potuto aggiornare il tuo account"
" perché il sito richiede di verificare i tuoi dati personali. Fai il login "
"su questo sito e aggiorna i campi richiesti. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (427): We could not update your account due to the "
"site requiring you to view a new promotion. Please log in to the site and "
"click through to your account overview page to update the account.  We "
"apologize for the inconvenience."
msgstr ""
"Nuova verifica richiesta (427): Non abbiamo potuto aggiornare il tuo account"
" perché il sito richiede di visualizzare una nuova promozione. Fai il login "
"sul sito e clicca sulla pagina di presentazione del tuo account per "
"aggiornarlo. Ci scusiamo per il disagio."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (428): We could not update your account due to the "
"site requiring you to accept a new Terms & Conditions. Please log in to the "
"site and read and accept the T&C."
msgstr ""
"Nuova verifica richiesta (428): Non abbiamo potuto aggiornare il tuo account"
" perché il sito ti chiede di accettare i nuovi Termini e Condizioni. Fai il "
"login su questo sito e leggi e accetta i Termini e Condizioni. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (433): Auto registration is not complete. "
"Please complete your registration at the end site. Once completed, please "
"complete adding this account."
msgstr ""
"La registrazione richiede la tua attenzione (433): La registrazione "
"automatica non è completata. Completa la registrazione sul sito finale. Una "
"volta completata, completa il processo di aggiunta di questo account. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (434): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"La registrazione richiede la tua attenzione (434): La tua registrazione "
"automatica non può essere completata, dovete intervenire. Controlla di nuovo"
" le informazioni di registrazione per completare il processo. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (435): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"La registrazione richiede la tua attenzione (435): La tua registrazione "
"automatica non può essere completata, dovete intervenire. Controlla di nuovo"
" le informazioni di registrazione per completare il processo. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Request Timed Out (508): We are sorry, your request timed out due to "
"technical reasons. Please try again."
msgstr ""
"Richiesta scaduta (508): Siamo spiacenti, la tua richiesta è scaduta per "
"motivi tecnici. Prova di nuovo. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Requested Account Type Not Found (414): We could not find your requested "
"account. You may have selected a similar site under a different category by "
"accident in which case you should select the correct site."
msgstr ""
"Tipo di account richiesto non trovato (414): Non abbiamo trovato l'account "
"da te richiesto. Forse hai selezionato un sto simile in una catgoria diversa"
" per errore. Devi selezionare il sito corretto. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Server not reachable, please try again later"
msgstr "Server non raggiungibile. Riprova più tardi."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Down for Maintenance(424):We were unable to update your account as the "
"site is temporarily down for maintenance. We apologize for the "
"inconvenience.  This problem is typically resolved in a few hours. Please "
"try later."
msgstr ""
"Sito non disponibile per causa di manutenzione (424): Non abbiamo potuto "
"aggiornare il tuo account, perché il sito è temporaneamente indisponibile a "
"causa di manutenzione. Ci scusiamo per il disagio. Questo problema viene "
"solitamente risolto in alcune ore. Riprova più tardi."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Available (411):The site no longer provides online services "
"to its customers.  Please delete this account."
msgstr ""
"Sito non îù disponibile (411): Il sito non fornisce più servizi online ai "
"propri clienti. Elimina questo account. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Supported (430):This site is no longer supported for data "
"updates. Please deactivate or delete your account. We apologize for the "
"inconvenience."
msgstr ""
"Sito non più supportato (430): Questo sito non è più supportato per gli "
"aggiornamenti dei dati. Disattiva o elimina il tuo account. Ci scusiamo per "
"il disagio. "

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Not Supported (505): We currently does not support the security system "
"used by this site. We apologize for any inconvenience. Check back "
"periodically if this situation has changed."
msgstr ""
"Sito non supportato (505): Attualmente non supportiamo il sistema di "
"sicurezza usato da questo sito. Ci scusiamo per il disagio. Controlla "
"periodicamente se la situazione è cambiata. "

#. module: account_yodlee
#: model:ir.actions.client,name:account_yodlee.yodlee_widget
msgid "Synchronization process completed"
msgstr "Processo di sincronizzazione completato"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Timeout: the server did not reply within 30s"
msgstr "Timeout: in server non ha risposto entro 30s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Update Request Canceled(405):Your account was not updated because you "
"canceled the request."
msgstr ""
"Richiesta di aggiornamento annullata (405): Il tuo account non è stato "
"aggiornato perché hai annullato la richiesta. "

#. module: account_yodlee
#: model:ir.model.fields.selection,name:account_yodlee.selection__account_online_provider__provider_type__yodlee
msgid "Yodlee"
msgstr "Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Yodlee Account Status"
msgstr "Stato account Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_status_code
msgid "Yodlee Status Code"
msgstr "Codice di stato Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_access_token
msgid "Yodlee access token"
msgstr "Token di accesso Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_login
msgid "Yodlee login"
msgstr "Login Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_password
msgid "Yodlee password"
msgstr "Password Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_access_token
msgid "access_token"
msgstr "access_token"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "message: %s"
msgstr "messaggio: %s"
