# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* account_yodlee
# 
# Translators:
# Linkup <link-up@naver.com>, 2019
# JH CHOI <hwangtog@gmail.com>, 2020
# 
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server saas~12.5+e\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-08-26 08:04+0000\n"
"PO-Revision-Date: 2019-08-26 09:34+0000\n"
"Last-Translator: JH CHOI <hwangtog@gmail.com>, 2020\n"
"Language-Team: Korean (https://www.transifex.com/odoo/teams/41243/ko/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: ko\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "(Diagnostic: %r for URL %s)"
msgstr "(진단 : %s URL에 대한 %r)"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Account"
msgstr "계정"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Already Registered (436):Your Auto-Registration could not be "
"completed because the site reports that your account is already registered."
"  Please log in to the site to confirm and then complete the site addition "
"process with the correct login information."
msgstr ""
"계정이 이미 등록되었습니다 (436) : 사이트에서 계정이 이미 등록되어 있다고 보고하여 자동 등록을 완료 할 수 없습니다. 사이트에 "
"로그인하여 확인한 다음 올바른 로그인 정보로 사이트 추가 프로세스를 완료하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Locked (407): We could not update your account because it appears "
"your account has been locked. This usually results from too many "
"unsuccessful login attempts in a short period of time. Please visit the site"
" or contact its customer support to resolve this issue.  Once done, please "
"update your account credentials in case they are changed."
msgstr ""
"계정 잠금 (407) : 계정이 잠긴 것으로 보이므로 계정을 업데이트 할 수 없습니다. 이는 일반적으로 단기간에 너무 많은 로그인 시도 "
"실패로 인해 발생합니다. 이 문제를 해결하려면 사이트를 방문하거나 고객 지원부에 문의하십시오. 완료되면 계정 자격 증명이 변경될 경우 "
"이를 업데이트하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Not Found(408): We're sorry, we couldn't find any accounts for you "
"at the site. Please log in at the site and confirm that your account is set "
"up, then try again."
msgstr ""
"계정을 찾을 수 없음 (408) : 죄송합니다. 사이트에서 귀하를 위한 계정을 찾을 수 없습니다. 사이트에 로그인하여 계정 설정을 확인한"
" 후 다시 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Reported Closed (422): We were unable to update your account "
"information because it appears one or more of your related accounts have "
"been closed.  Please deactivate or delete the relevant account and try "
"again."
msgstr ""
"계정이 폐쇄 된 것으로보고 됨 (422) : 하나 이상의 관련 계정이 폐쇄된 것으로 보이므로 계정 정보를 업데이트할 수 없습니다. 관련 "
"계정을 비활성화하거나 삭제한 후 다시 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Account Type Not Supported(417):The type of account we found is not "
"currently supported.  Please remove this site and add as a  manual account."
msgstr ""
"지원되지 않는 계정 유형 (417) : 찾은 계정 유형은 현재 지원되지 않습니다. 이 사이트를 제거하고 수동으로 계정을 추가하십시오."

#. module: account_yodlee
#: model:ir.model.fields,help:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Active/Inactive on Yodlee system"
msgstr "Yodlee 시스템에서 활성/비활성"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "An Error has occurred (code %s)"
msgstr "오류가 발생했습니다 (코드 %s)"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_res_company
msgid "Companies"
msgstr "회사"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Could not make sense of parameters: %s"
msgstr "매개 변수를 이해할 수 없습니다 : %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (402): We could not update your account "
"because your username and/or password were reported to be incorrect.  Please"
" re-verify your username and password."
msgstr ""
"자격 증명 재확인 필요 (402) : 사용자 이름 및 비밀번호가 잘못 보고되어 계정을 업데이트할 수 없습니다. 사용자 이름과 비밀번호를 "
"다시 확인하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Credential Re-Verification Required (420):The site has merged with another. "
"Please re-verify your credentials at the site and update the same."
msgstr ""
"자격 증명 재확인 필요 (420) : 사이트가 다른 사이트와 병합되었습니다. 사이트에서 자격 증명을 다시 확인하고 동일하게 "
"업데이트하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s"
msgstr "오류 %s, 메시지 : %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Error %s, message: %s, reference code: %s"
msgstr "오류 %s, 메시지 : %s, 참조 코드 : %s"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Home Value Not Found (511): The site is unable to provide home value for "
"your property. We suggest you to delete this site."
msgstr ""
"홈 값을 찾을 수 없음(511) : 사이트에서 사용자의 재산에 대한 홈 값을 제공할 수 없습니다. 이 사이트를 삭제하는 것이 좋습니다."

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_journal
msgid "Interface for Online Account Journal"
msgstr "온라인 계정 분개장을 위한 인터페이스"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Invalid Language Setting (421): The language setting for your site account "
"is not English. Please visit the site and change the language setting to "
"English."
msgstr ""
"잘못된 언어 설정 (421) : 사이트 계정의 언어 설정이 영어가 아닙니다. 사이트를 방문하여 언어 설정을 영어로 변경하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Additional Authentication Enrollment Required (521) : Please "
"enroll in the new security authentication system, <Account Name> has "
"introduced. Ensure your account settings in <Cobrand> are updated with this "
"information."
msgstr ""
"MFA 오류 : 추가 인증 등록 필요 (521) : 새 보안 인증 시스템에 <Account Name>등록하십시오. 계정 설정이 "
"<Cobrand>이 정보로 업데이트되었는지 확인합니다."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Expired (524):We're sorry, the "
"authentication information you provided has expired. Please try again."
msgstr "MFA 오류 : 인증 정보 만료 (524) : 죄송합니다. 제공한 인증 정보가 만료되었습니다. 다시 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (520):We're sorry, the site "
"indicates that the additional authentication information you provided is "
"incorrect. Please try updating your account again."
msgstr ""
"MFA 오류 : 잘못된 인증 정보 (520) : 죄송합니다. 사이트에서 제공한 추가 인증 정보가 잘못되었음을 나타냅니다. 계정을 다시 "
"업데이트하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Incorrect (523):We're sorry, the "
"authentication information you  provided is incorrect. Please try again."
msgstr "MFA 오류 : 잘못된 인증 정보 (523) : 죄송합니다. 제공한 인증 정보가 잘못되었습니다. 다시 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Required (519): Your account was not "
"updated as your authentication information like security question and answer"
" was unavailable or incomplete. Please update your account settings."
msgstr ""
"MFA 오류 : 인증 정보 필요 (519) : 보안 질문 및 답변과 같은 인증 정보를 사용할 수 없거나 불완전하여 계정이 업데이트되지 "
"않았습니다. 계정 설정을 업데이트하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Authentication Information Unavailable (518):Your account was not"
" updated as the required additional authentication information was "
"unavailable. Please try now."
msgstr ""
"MFA 오류 : 인증 정보를 사용할 수 없음 (518) : 필요한 추가 인증 정보를 사용할 수 없어 계정이 업데이트되지 않았습니다. 지금"
" 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Credential Re-Verification Required (526): We could not update "
"your account because your username/password or additional security "
"credentials are incorrect. Please try again."
msgstr ""
"MFA 오류 : 자격 증명 재확인 필요 (526) : 사용자 이름/암호 또는 추가 보안 자격 증명이 잘못되어 계정을 업데이트할 수 "
"없습니다. 다시 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Problem Updating Account (525): We could not update your account "
"for technical reasons. This type of error is usually resolved in a few days."
" We apologize for the inconvenience. Please try again later."
msgstr ""
"MFA 오류 : 계정 업데이트 문제 (525) : 기술적 이유로 계정을 업데이트할 수 없습니다. 이 유형의 오류는 일반적으로 며칠 내에 "
"해결됩니다. 불편을 드려 죄송합니다. 나중에 다시 시도하세요."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Request Timed Out (522) :Your request has timed out as the "
"required security information was unavailable or was not provided within the"
" expected time. Please try again."
msgstr ""
"MFA 오류 : 요청 시간 초과 (522) : 필요한 보안 정보를 사용할 수 없거나 예상 시간 내에 제공되지 않아 요청 시간이 "
"초과되었습니다. 다시 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"MFA error: Site Device Information Expired(509): We're sorry, we can't "
"update your account because your token is no longer valid at the site. "
"Please update your information and try again, or contact customer support."
msgstr ""
"MFA 오류 : 사이트 장치 정보 만료 (509) : 죄송합니다. 사이트에서 토큰이 더 이상 유효하지 않아 계정을 업데이트 할 수 "
"없습니다. 정보를 업데이트한 후 다시 시도하거나 고객 지원에 문의하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Multiple User Logins(416): We attempted to update your account, but another "
"session was already established at the same time.  If you are currently "
"logged on to this account directly, please log off and try after some time"
msgstr ""
"여러 사용자 로그인 (416) : 계정을 업데이트하려고 했으나 다른 세션이 이미 설정되었습니다. 현재 이 계정에 직접 로그온 한 경우 "
"로그 오프한 후 잠시 후 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"New Login Information Required(506):We're sorry, to log in to this site, you"
" need to provide additional information. Please update your account and try "
"again."
msgstr ""
"새 로그인 정보 필요 (506) : 죄송합니다. 이 사이트에 로그인하려면 추가 정보를 제공해야 합니다. 계정을 업데이트하고 다시 "
"시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Account Found (423): We were unable to detect an account. Please verify "
"that you account information is available at this time and If the problem "
"persists, please contact customer support at online@odoo.com for further "
"assistance."
msgstr ""
"계정을 찾을 수 없음 (423) : 계정을 찾을 수 없습니다. 현재 계정 정보가 있는지 확인하고 문제가 지속되면 "
"online@odoo.com의 고객 지원 센터에 추가 지원을 요청하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"No Payees Found(512):Your request cannot be completed as no payees were "
"found in your account."
msgstr "수취인을 찾을 수 없음 (512) : 계정에 수취인이 없어서 요청을 완료할 수 없습니다."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Online institution"
msgstr "온라인 기관"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Please configure an email in the company settings."
msgstr "회사 설정에서 이메일을 구성하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (406): We could not update your account because the"
" site requires you to perform some additional action. Please visit the site "
"or contact its customer support to resolve this issue. Once done, please "
"update your account credentials in case they are changed else try again."
msgstr ""
"계정 업데이트 문제 (406) : 사이트에서 추가 조치를 수행해야하므로 계정을 업데이트할 수 없습니다. 이 문제를 해결하려면 사이트를 "
"방문하거나 고객 지원부에 문의하십시오. 완료되면 계정 자격 증명을 변경한 경우 다시 업데이트하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account (517): We are sorry, there was a technical problem "
"updating your account. Please try again."
msgstr "계정 업데이트 문제 (517) : 죄송합니다. 계정을 업데이트하는 데 기술적인 문제가 있습니다. 다시 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(401):We're sorry, your request timed out. Please "
"try again."
msgstr "계정 업데이트 문제 (401) : 죄송합니다. 요청 시간이 초과되었습니다. 다시 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(403):We're sorry, there was a technical problem "
"updating your account. This kind of error is usually resolved in a few days."
" Please try again later."
msgstr ""
"계정 업데이트 문제 (403) : 죄송합니다. 계정을 업데이트하는 데 기술적인 문제가 있습니다. 이러한 종류의 오류는 일반적으로 며칠 "
"내에 해결됩니다. 나중에 다시 시도하세요."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(404):We're sorry, there was a technical problem "
"updating your account. Please try again later."
msgstr "계정 업데이트 문제 (404) : 죄송합니다. 계정을 업데이트하는 데 기술적인 문제가 있습니다. 나중에 다시 시도하세요."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(409): We could not update your account because the "
"end site is experiencing technical difficulties."
msgstr "계정 업데이트 문제 (409) : 최종 사이트에 기술적인 문제가있어 계정을 업데이트할 수 없습니다."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(412): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr "계정 업데이트 문제 (412) : 사이트에 기술적인 문제가 있어 계정을 업데이트할 수 없습니다."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(413):We're sorry, we couldn't update your account "
"at the site because of a technical issue. This type of problem is usually "
"resolved in a few days. Please try again later."
msgstr ""
"계정 업데이트 문제 (413) : 기술적인 문제로 인해 사이트에서 계정을 업데이트할 수 없습니다. 이 유형의 문제는 일반적으로 며칠 내에"
" 해결됩니다. 나중에 다시 시도하세요."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(415): We could not update your account because the "
"site is experiencing technical difficulties."
msgstr "계정 업데이트 문제 (415) : 사이트에 기술적인 문제가있어 계정을 업데이트할 수 없습니다."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(418): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr "계정 업데이트 문제 (418) : 사이트에 기술적인 문제가 있어 계정을 업데이트할 수 없습니다. 나중에 다시 시도해 주세요."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(419):We're sorry, we couldn't update your account "
"because of unexpected variations at the site. This kind of problem is "
"usually resolved in a few days. Please try again later."
msgstr ""
"계정 업데이트 문제 (419) : 죄송합니다. 사이트의 예기치 않은 변형으로 인해 계정을 업데이트할 수 없습니다. 이런 종류의 문제는 "
"보통 며칠 안에 해결됩니다. 나중에 다시 시도하세요."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(425): We could not update your account because the "
"site is experiencing technical difficulties. Please try later."
msgstr "계정 업데이트 문제 (425) : 사이트에 기술적인 문제가 있어 계정을 업데이트할 수 없습니다. 나중에 다시 시도해 주세요."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(426): We could not update your account for "
"technical reasons. This type of error is usually resolved in a few days. We "
"apologize for the inconvenience."
msgstr ""
"계정 업데이트 문제 (426) : 기술적 이유로 계정을 업데이트할 수 없습니다. 이 유형의 오류는 일반적으로 며칠 내에 해결됩니다. "
"불편을 드려 죄송합니다."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Problem Updating Account(507):We're sorry, Yodlee has just started providing"
" data updates for this site, and it may take a few days to be successful as "
"we get started. Please try again later."
msgstr ""
"계정 업데이트 문제 (507) : 죄송합니다. Yodlee가 이 사이트에 대한 데이터 업데이트를 제공하기 시작했으며 시작하는 데 며칠이 "
"걸릴 수 있습니다. 나중에 다시 시도하세요."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Property Record Not Found (510): The site is unable to find any property "
"information for your address. Please verify if the property address you have"
" provided is correct."
msgstr ""
"부동산 기록을 찾을 수 없음 (510) : 사이트에서 귀하의 주소에 대한 부동산 정보를 찾을 수 없습니다. 제공한 부동산 주소가 정확한지"
" 확인하십시오."

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_provider__provider_type
msgid "Provider Type"
msgstr "공급자 유형"

#. module: account_yodlee
#: model:ir.model,name:account_yodlee.model_account_online_provider
msgid "Provider for online account synchronization"
msgstr "온라인 계정 동기화 공급자"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-Verification Required (429): We could not update your account due to the "
"site requiring you to verify your personal information. Please log in to the"
" site and update the fields required."
msgstr ""
"재확인 필요 (429) : 사이트에서 개인 정보를 확인해야 하므로 계정을 업데이트할 수 없습니다. 사이트에 로그인하여 필요한 필드를 "
"업데이트하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (427): We could not update your account due to the "
"site requiring you to view a new promotion. Please log in to the site and "
"click through to your account overview page to update the account.  We "
"apologize for the inconvenience."
msgstr ""
"재확인 필요 (427) : 사이트에서 새 프로모션을 보도록 요청하여 계정을 업데이트할 수 없습니다. 사이트에 로그인하고 계정 개요 "
"페이지를 클릭하여 계정을 업데이트하십시오. 불편을 드려 죄송합니다."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Re-verification Required (428): We could not update your account due to the "
"site requiring you to accept a new Terms & Conditions. Please log in to the "
"site and read and accept the T&C."
msgstr ""
"재확인 필요 (428) : 새로운 이용 약관에 동의해야 하는 사이트로 인해 계정을 업데이트할 수 없습니다. 사이트에 로그인하여 이용 "
"약관을 읽고 동의하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (433): Auto registration is not complete. "
"Please complete your registration at the end site. Once completed, please "
"complete adding this account."
msgstr ""
"등록이 필요합니다 (433) : 자동 등록이 완료되지 않았습니다. 최종 사이트에서 등록을 완료하십시오. 완료되면 이 계정 추가를 "
"완료하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (434): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"등록시 주의가 필요함 (434) : 자동 등록을 완료할 수 없어서 추가 입력이 필요합니다. 절차를 완료하려면 등록 정보를 다시 "
"확인하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Registration Requires Attention (435): Your Auto-Registration could not be "
"completed and requires further input from you.  Please re-verify your "
"registration information to complete the process."
msgstr ""
"등록에 주의 필요 (435) : 자동 등록을 완료할 수 없어서 추가 입력이 필요합니다. 절차를 완료하려면 등록 정보를 다시 확인하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Request Timed Out (508): We are sorry, your request timed out due to "
"technical reasons. Please try again."
msgstr "요청 시간 초과 (508) : 죄송합니다. 기술적 이유로 인해 요청 시간이 초과되었습니다. 다시 시도하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Requested Account Type Not Found (414): We could not find your requested "
"account. You may have selected a similar site under a different category by "
"accident in which case you should select the correct site."
msgstr ""
"요청한 계정 유형을 찾을 수 없음 (414) : 요청한 계정을 찾을 수 없습니다. 실수로 다른 카테고리에서 유사한 사이트를 선택했을 수 "
"있습니다.이 경우 올바른 사이트를 선택해야 합니다."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Server not reachable, please try again later"
msgstr "서버에 연결할 수 없습니다. 나중에 다시 시도하십시오"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Down for Maintenance(424):We were unable to update your account as the "
"site is temporarily down for maintenance. We apologize for the "
"inconvenience.  This problem is typically resolved in a few hours. Please "
"try later."
msgstr ""
"유지 관리를위한 사이트 중단 (424) : 유지 관리를 위해 사이트가 일시적으로 다운되어 계정을 업데이트할 수 없습니다. 불편을 드려 "
"죄송합니다. 이 문제는 일반적으로 몇 시간 내에 해결됩니다. 나중에 다시 시도해 주세요."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Available (411):The site no longer provides online services "
"to its customers.  Please delete this account."
msgstr ""
"더 이상 사용할 수없는 사이트 (411) : 이 사이트는 더 이상 고객에게 온라인 서비스를 제공하지 않습니다. 이 계정을 삭제하십시오."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site No Longer Supported (430):This site is no longer supported for data "
"updates. Please deactivate or delete your account. We apologize for the "
"inconvenience."
msgstr ""
"더 이상 지원되지 않는 사이트 (430) : 이 사이트는 더 이상 데이터 업데이트를 지원하지 않습니다. 계정을 비활성화하거나 "
"삭제하십시오. 불편을 드려 죄송합니다."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Site Not Supported (505): We currently does not support the security system "
"used by this site. We apologize for any inconvenience. Check back "
"periodically if this situation has changed."
msgstr ""
"지원되지 않는 사이트 (505) : 현재 이 사이트에서 사용하는 보안 시스템을 지원하지 않습니다. 불편을 끼쳐 드려 죄송합니다. 이 "
"상황이 바뀐 경우 주기적으로 다시 확인하십시오."

#. module: account_yodlee
#: model:ir.actions.client,name:account_yodlee.yodlee_widget
msgid "Synchronization process completed"
msgstr "동기화 프로세스 완료"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "Timeout: the server did not reply within 30s"
msgstr "시간 초과 : 서버가 30초 내에 응답하지 않았습니다."

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid ""
"Update Request Canceled(405):Your account was not updated because you "
"canceled the request."
msgstr "요청 업데이트 취소 (405) : 요청을 취소하여 계정이 업데이트되지 않았습니다."

#. module: account_yodlee
#: model:ir.model.fields.selection,name:account_yodlee.selection__account_online_provider__provider_type__yodlee
msgid "Yodlee"
msgstr "Yodlee"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_account_status
msgid "Yodlee Account Status"
msgstr "Yodlee 계정 상태"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_account_online_journal__yodlee_status_code
msgid "Yodlee Status Code"
msgstr "Yodlee 상태 코드"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_access_token
msgid "Yodlee access token"
msgstr "Yodlee 사용 권한 토큰"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_login
msgid "Yodlee login"
msgstr "Yodlee 로그인"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_user_password
msgid "Yodlee password"
msgstr "Yodlee 비밀번호"

#. module: account_yodlee
#: model:ir.model.fields,field_description:account_yodlee.field_res_company__yodlee_access_token
msgid "access_token"
msgstr "access_token"

#. module: account_yodlee
#: code:addons/account_yodlee/models/yodlee.py:0
#, python-format
msgid "message: %s"
msgstr "메시지 : %s"
